require("arthurdw.keymaps")
require("arthurdw.plugins")
require("arthurdw.cmp")
require("arthurdw.lsp")
require("arthurdw.treesitter")
require("arthurdw.comment")
require("arthurdw.autopairs")
require("arthurdw.nvim-tree")
require("arthurdw.bufferline")
require("arthurdw.toggleterm")
require("arthurdw.refactoring")
require("arthurdw.renamer")
require("arthurdw.treesitter-context")
require("arthurdw.indent-blankline")

-- setups
require("neoscroll").setup()
require("nvim-lastplace").setup({})
